version: '3.8'
services:
  customermanagementsvc:
    image: "tothadam98/kuka-customermanagementsvc:latest"
    restart: always
    ports:
      - '8080:8080'
    environment:
      - JAVA_OPTS=
    depends_on:
      - db
    volumes:
      - customer:/var/lib/customer/service
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Resource
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
  customer:
    driver: local